version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - dagger-cache:/root/.dagger
    restart: unless-stopped

volumes:
  dagger-cache:
