
line-length = 120
target-version = "py312"

[lint]
extend-select = ["F", "I", "Q"]
ignore = ["E722"]

[format]
quote-style = "single"

[lint.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"
inline-quotes = "single"

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
